export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const REFRESH_TOKEN_REPOSITORY = Symbol('REFRESH_TOKEN_REPOSITORY');
export const PRESCRIPTION_REPOSITORY = Symbol('PRESCRIPTION_REPOSITORY');
export const AUDIT_LOG_REPOSITORY = Symbol('AUDIT_LOG_REPOSITORY');
export const METRICS_REPOSITORY = Symbol('METRICS_REPOSITORY');
export const PRESCRIPTION_PDF_STRATEGY = Symbol('PRESCRIPTION_PDF_STRATEGY');
